export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST"
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS"
export const USER_LOGIN_FAIlURE = "USER_LOGIN_FAIlURE"
export const USER_LOGOUT = "USER_LOGOUT"